### ISSUE TITLE
Unity 2020 Beta 10 and HDR - Colors are not correct for the Gizmo (Play & Run modes)

### ISSUE THREAD

**Issue by itssource** [yasirkula/UnityRuntimeSceneGizmo#1]
Can you test against Unity 2020 Beta 10 and High Definition RP Version 9.0.0-preview.13 - April 07, 2020 package?

I am seeing colors not being correctly set for the Gizmo in Design, Play, or Build times.

Screen shot of view of Gizmo seeing.
https://ibb.co/6nJqkgy

**Comment by yasirkula** [comment]
A post processing effect might somehow be affecting it. I will check it out but I'd prefer testing it when 2020.1 officially releases.

**Comment by itssource** [comment]
If you could check it out sooner that would be big for our project. Also, on Unity 2020 build I noticed the Gizmo is not showing with the latest HDRP v. 9 preview 13 in use. Any ideas why that would be? I'm not seeing any issues like this with other UI or packages in use.

**Comment by yasirkula** [comment]
This solution worked for me:

- open Plugins/RuntimeSceneGizmo/Prefabs/SceneGizmo.prefab and set Gizmo Camera's "Volume Layer Mask" to None
- inside your HDRP settings asset, change Color Buffer Format to R16G16B16A16 since it is the only format that supports alpha channel in RenderTextures
- to fix the invisibility issue in the build, try adding a dummy Image object to the Canvas

**Comment by itssource** [comment]
I checked the Plugins folder (reimported to make sure all of the asset was in my project). But the odd thing is I do not see Prefabs (/Plugins/RuntimeSceneGizmo/[ prefabs is not here]). Any idea why? 

Update:
(I'm using Unity Asset Store package, should I use the Github project instead?)

**Comment by yasirkula** [comment]
Both versions have the same file structure, that's weird. Where did you find the GizmoRenderer prefab then?

**Comment by itssource** [comment]
I got it from the Assets > RunttimeSceneGizmo (but it's not in the Plugin folder). Seems a different structure when the assets is gotten from Unity Asset Store?

**Comment by yasirkula** [comment]
I've just imported it to my project via Package Manager-My Assets and it is imported correctly at Assets/Plugins/RuntimeSceneGizmo (I'm using 2019.3.6f1). Unless someone moved the plugin to Assets/RuntimeSceneGizmo manually, it really shouldn't happen. Maybe Asset Store in 2020.1 somehow moves imported assets from Assets/Plugins to Assets/, I'll check it out once 2020.1 is publicly released.

**Comment by itssource** [comment]
It's working now! Thank you so much yasirkula. I did the Color Buffer only. And now it shows up with proper (no square colored background) transparency around the gizmos. I left my project structure as-is. This is huge. Love the assets. Thanks again!

**Comment by mybmgithub** [comment]
Thanks again!

**Comment by yasirkula** [comment]
You are welcome! FYI, Setting "Volume Layer Mask" to None disables post-processing on the gizmo.

**Comment by itssource** [comment]
Ouch. lol. Glad I did not do that. Thanks for the heads up.

Thanks again.
