### ISSUE TITLE
Feature Request - Make clicking on an Axis "Cone" like Unity's in-Editor Gizmo

### ISSUE THREAD

**Issue by itssource** [yasirkula/UnityRuntimeSceneGizmo#2]
Here's one other thing I saw that would help a lot for our users (of our application with this Gizmo). Is that if it acted more like Unity in one other way. 

1. Click on one of the cones while the Gizmo is rotated in any direction
2. Click on one of the cones again.

Result: 
The Gizmo sets to be along the clicked axis or related axis to that action. 

Two images here to demonstrate this need.

https://ibb.co/qYgb0Sv
https://ibb.co/LhkQMQL

This will help our (or any) users quickly get a 2D like view like Unity Editor does. (no manual rotation).

Do think this is something you could add in the short-term?

**Comment by yasirkula** [comment]
Unless I misunderstood the Issue, the example scene behaves exactly like this. I'd recommend you to check it out.

**Comment by itssource** [comment]
That is odd. Your demo does work as I would expect, this way already. Now I have to figure out why my version is not. Maybe I made some change to the Inspector area to affect this issue? Thanks for the follow-up. I'll follow-up if/when I get a fix. If you come up with an idea why it may not work and just rotate on that same rotation, that would be great. Thanks again.

**Comment by itssource** [comment]
I figured it out yasirkula. Camera Movement Script was not on the main camera. ;-( I must have removed it when doing some refactoring. Sorry about that. That one was on me. It's working as expected now. Thanks for all the help. If you have a PayPal I would like to send you some coffee money. 

I think I know what happened. I probably removed it because it was "conflicting" with my own camera script. Looks like I just need to see how to work them together or combine them.

**Comment by yasirkula** [comment]
The CameraGizmoListener script may not be suitable for other camera setups. In my setup, camera has a parent object and it also has a negative Z position offset. So, whenever I rotate the parent object, it will look like the camera is orbiting around the parent object.

If your camera setup is different, you'd have to create a new script, copy CameraGizmoListener's contents to it and modify it to work with your own camera system.

**Comment by itssource** [comment]
Here's the (I think it will be. So far so good) final code adjustment I made to your script. 

I added, ` && Input.GetKey(KeyCode.LeftAlt)`



using UnityEngine;

namespace RuntimeSceneGizmo
{
	public class CameraMovement : MonoBehaviour
	{
#pragma warning disable 0649
		[SerializeField]
		private float sensitivity = 0.5f;
#pragma warning restore 0649

		private Vector3 prevMousePos;
		private Transform mainCamParent;

		private void Awake()
		{
			mainCamParent = Camera.main.transform.parent;
		}

		private void Update()
		{
			if( Input.GetMouseButtonDown(0) )
				prevMousePos = Input.mousePosition;
			else if( Input.GetMouseButton(0) && Input.GetKey(KeyCode.LeftAlt) )
			{
				Vector3 mousePos = Input.mousePosition;
				Vector2 deltaPos = ( mousePos - prevMousePos ) * sensitivity;

				Vector3 rot = mainCamParent.localEulerAngles;
				while( rot.x > 180f )
					rot.x -= 360f;
				while( rot.x < -180f )
					rot.x += 360f;

				rot.x = Mathf.Clamp( rot.x - deltaPos.y, -89.8f, 89.8f );
				rot.y += deltaPos.x;
				rot.z = 0f;

				mainCamParent.localEulerAngles = rot;
				prevMousePos = mousePos;
			}
		}
	}
}

**Comment by itssource** [comment]
> The CameraGizmoListener script may not be suitable for other camera setups. In my setup, camera has a parent object and it also has a negative Z position offset. So, whenever I rotate the parent object, it will look like the camera is orbiting around the parent object.
> 
> If your camera setup is different, you'd have to create a new script, copy CameraGizmoListener's contents to it and modify it to work with your own camera system.

Thanks again. And for the tip here. This is all very help to us. I can't thank you enough for the help.
