### ISSUE TITLE
SceneGizmo GameObject Destroyed On SwitchScene.

### ISSUE THREAD

**Issue by KumoKyaku** [yasirkula/UnityRuntimeSceneGizmo#3]
![image](https://user-images.githubusercontent.com/15962980/124109714-080fbd00-da9a-11eb-92d5-25d723ffa06b.png)
if GizemoRenderer dont destory on load , SceneGizmo GameObject Destroyed On SwitchScene. 
Controller is missing.

**Comment by KumoKyaku** [comment]
![image](https://user-images.githubusercontent.com/15962980/124110505-e06d2480-da9a-11eb-86d2-73c683c48511.png)
Another usage experience , on editor mode ,image is white block,a little uncomfortable

**Comment by yasirkula** [comment]
There is no good way to detect when an object is DontDestroyOnLoad'ed so I think this is a special case which can only be resolved by manually modifying the code. You can simply add `DontDestroyOnLoad(controller.gameObject);` to this function: https://github.com/yasirkula/UnityRuntimeSceneGizmo/blob/44f719a7ad6ec19918cf8f4e18ea822ee99fc0d1/Plugins/RuntimeSceneGizmo/Scripts/SceneGizmoRenderer.cs#L51-L57

As for the white block, it helps see where the gizmo will be located at. If you don't want that, you can set its Color transparent and then call `imageHolder.color = Color.white;` inside Awake function.
